### ISSUE TITLE
BUG: Jitter on Windows machines

### ISSUE THREAD

**Issue by larsoner** [spatialaudio/python-rtmixer#14]
I have tested `python-rtmixer` on Linux and found (with a scope) sub-millisecond jitter between a parallel port trigger and the audio start, assuming I call:
```
mixer.play_buffer(..., start=mixer.time + fixed_delay)
```
with a `fixed_delay` that is sufficiently large, i.e. probably bigger than the sound card ALSA buffer (on Linux with my built-in sound card I use 10 ms but could probably go lower).

On Windows, however, I cannot get this behavior on any backend (WDM, MME, WASAPI) or multiple sound cards (motherboard built-in Realtek ALC1220, or some USB sound cards). There is always some jitter, even when I set the fixed delay. I can see the delay works, because as I increase it, the latency increases. But jitter never goes down.

Is PortAudio/rtmixer on Windows supposed to behave this way? Any ideas why this might be happening?

**Comment by mgeier** [comment]
Thanks for testing this, this is very interesting!

Out of curiosity, about how much sub-millisecond is the jitter on Linux?

I would hope that it's significantly below a millisecond.

> Is PortAudio/rtmixer on Windows supposed to behave this way?

I'm not sure, but according to what I've heard, I'm not surprised.

> Any ideas why this might be happening?

I guess because the used APIs were not designed for that.

You could try WASAPI in "exclusive" mode: https://python-sounddevice.readthedocs.io/en/0.3.13/api.html#sounddevice.WasapiSettings

This is supposed to give you lower latencies, but I guess the jitter should also be lower.

Do you have ASIO drivers for your sound card(s)? Those should also typically have much better performance.

**Comment by larsoner** [comment]
> You could try WASAPI in "exclusive" mode

I will give this a shot. But really it seems like exclusive or not shouldn't matter if the stream time is known. But maybe being in non-exclusive mode means the stream time is wrong...?

> Do you have ASIO drivers for your sound card(s)? Those should also typically have much better performance.

I used ASIO4ALL for my Realtek built-in audio and native ASIO drivers for my PreSonus AudioBox USB. And a friend of mine used an RME PCIe card (ASIO) has seen the same thing. Hence why I wonder if the timing is just somehow broken on Windows.

But it can't be totally broken, since increasing the delay in the `start` value does actually delay the signal...

**Comment by larsoner** [comment]
> Out of curiosity, about how much sub-millisecond is the jitter on Linux?

Once it was under 1 ms I didn't look too closely. My method of timing checking was to change the parallel port value in Python, then tell RTMixer to play at `stream_time + delay`. There are some Python calls in there that could contribute variability. I can check next time I have everything hooked up though.

**Comment by mgeier** [comment]
> But maybe being in non-exclusive mode means the stream time is wrong...?

I don't know, but I guess it's worth a shot to try "exclusive" mode.

I'm surprised that you get the same problem with native ASIO drivers ... but I don't know if there is anything that can be done to improve the situation.

> I wonder if the timing is just somehow broken on Windows.

Probably. But if that's the case, the problem should also appear when using PortAudio in a C or C++ application, right?

Anyway, you might want to ask at the PortAudio mailing list (http://portaudio.com/contacts.html) about that?

> There are some Python calls in there that could contribute variability.

Definitely. I guess there might even be a switch to a different Python thread (if there are multiple threads) or a run of the garbage collector?
I think this cannot be avoided, but maybe the number of Python instructions can be somehow reduced?

If you want to experiment with this, you can try to manually create an "action" (before taking the stream time!) and then use the `_enqueue()` method. You might even go a step further and directly put your "action" into the `_action_q`. And I guess the last step would be to directly call `_lib.PaUtil_WriteRingBuffer()`. But there will always be a few Python instructions left ...
If that's still not good enough, you'll have to abandon Python and use some compiled language.

If you find a way how the code can be optimized, please let me know!

**Comment by larsoner** [comment]
Okay running in exclusive WASAPI mode I get rock solid timing! Overlays of photodiode responses to a white flash (you can see a few went for two frames instead of one) in mostly red with the auditory click measurements in what ends up being rainbow (time relative to the parallel port trigger that occurred immediately after I told everything to "go"):

![image](https://user-images.githubusercontent.com/2365790/64435672-e78a9d80-d090-11e9-8602-6e1bcd763886.png)

This is assuming I impose a sufficiently long fixed delay (here 40 ms). FWIW I need to go up to about 30 ms fixed delay to have reliable no-jitter (even though the stream is reported as having a 2.7ms latency).

Still no luck with ASIO, though, still jitters there.

I dug around a tiny bit looking for `PaStreamCallbackTimeInfo` being unreliable, and found this. Do you think that it could be relevant?

https://github.com/mixxxdj/mixxx/blob/master/src/soundio/sounddeviceportaudio.cpp#L967-L1036

**Comment by larsoner** [comment]
See also PortAudio mailing list post (@mgeier feel free to correct me if I misrepresented anything):

https://lists.columbia.edu/pipermail/portaudio/2019-September/001915.html

**Comment by mgeier** [comment]
> Okay running in exclusive WASAPI mode I get rock solid timing!

That's great news!

> Still no luck with ASIO, though, still jitters there.

That's not great news, but still good to know.

TBH, I don't quite understand your screenshot. Would you mind explaining what those lines are and what's actually happening in your experiment?

BTW, this reminds me of something I saw just a few days ago: https://discourse.psychopy.org/t/new-release-3-2-0/8931

I haven't looked into the Psychtoolbox audio engine yet, it would be interesting to compare its performance to the `rtmixer` module.
And if it's really faster, I'd like to take some ideas from there and try to use them in `rtmixer`.

For now, I can only say they have significantly more C code (I think this is the main chunk: https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/PsychSourceGL/Source/Common/PsychPortAudio/PsychPortAudio.c).

There is some time-related code in the callback function, probably that's relevant here?

> This is assuming I impose a sufficiently long fixed delay (here 40 ms).

That's strange. I have no clue why such a large latency is necessary for getting small jitter.
But let's hope there are some answers on the PortAudio mailing list!

> Do you think that it could be relevant?

After a first reading, I don't quite understand it, so I don't know. I'll try to look into it again at a later point.

**Comment by larsoner** [comment]
> TBH, I don't quite understand your screenshot. Would you mind explaining what those lines are and what's actually happening in your experiment?

I repeatedly played a one-sample click with a one-frame flash while turning bit 1 high from the parallel port, with the aud/vis hooked up to inputs A and B of the scope and the parallel port as the external trigger. These are timed to all happen with no jitter by, in immediate succession:

1. Drawing a white screen, flipping the buffer, and waiting for the flip to return in Pyglet (waiting for it to return ensures that it has actually been sent to the display)
2. Triggering the audio to start in `mixer.time + 0.04` using `rtmixer`
3. Setting the parallel port bit 1 high
4. Waiting 10 ms
5. Setting parallel port bit 1 low (0)
6. Draw a black screen, flip the buffer
7. Wait ~500 ms

Then I repeated this a (couple?) dozen times to produce the plot above. The scope is triggered by the parallel port (this defines t=0). Shown relative to that are:

- "wavy" red lines are many overlaid triggered responses from a photodiode pointed at the screen, the ~3 (sometimes ~7) big peaks from ~34-50ms are presumably some tri-phasic response of my monitor to any given flipped buffer/frame.
- An impulsive (plus Gibbs ringing) click at ~41ms in rainbow color (this is many responses on top of each other and this is how the Picoscope overlay mode ended up blending them).

**Comment by larsoner** [comment]
... and yes that PsychToolbox backend very well might be doing something similar to what `rtmixer` does. It presumably would have to in order to achieve sub-ms jitter.

**Comment by larsoner** [comment]
Closing as a "probably portaudio" issue that can be maybe be solved someday!
