### ISSUE TITLE
compilation errors; c99 requirement

### ISSUE THREAD

**Issue by tgarc** [spatialaudio/python-rtmixer#2]
So I'm getting two compilation errors. First one is a straightfoward C99 requirement:

```
  build/temp.linux-x86_64-2.7/_rtmixer.c: In function 'callback':
  build/temp.linux-x86_64-2.7/_rtmixer.c:495: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:495: note: use option -std=c99 or -std=gnu99 to compile your code
  build/temp.linux-x86_64-2.7/_rtmixer.c:567: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:667: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:682: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:712: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:722: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:742: error: 'for' loop initial declarations are only allowed in C99 mode
  build/temp.linux-x86_64-2.7/_rtmixer.c:752: error: 'for' loop initial declarations are only allowed in C99 mode
  error: command 'gcc' failed with exit status 1
```

Which can be fixed by just setting `extra_compile_args=['-std=c99']` in rtmixer_build.py.

The other bug is a little more confusing:

```
_rtmixer.c: In function 'callback':
_rtmixer.c:517: error: 'struct action' has no member named 'action'
_rtmixer.c:518: error: 'struct action' has no member named 'action'
_rtmixer.c:569: error: 'struct action' has no member named 'action'
_rtmixer.c:661: error: 'struct action' has no member named 'buffer'
_rtmixer.c:705: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c:729: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c:735: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c:759: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c: In function '_cffi_checkfld_struct_action':
_rtmixer.c:1586: error: 'struct action' has no member named 'buffer'
_rtmixer.c:1587: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c:1588: error: 'struct action' has no member named 'action'
_rtmixer.c: At top level:
_rtmixer.c:1682: error: 'struct action' has no member named 'buffer'
_rtmixer.c:1683: error: 'struct action' has no member named 'buffer'
_rtmixer.c:1685: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c:1686: error: 'struct action' has no member named 'ringbuffer'
_rtmixer.c:1688: error: 'struct action' has no member named 'action'
_rtmixer.c:1689: error: 'struct action' has no member named 'action'
```
Looks like each of these fields are inside a `union` inside the `action` struct. Maybe this is a result of platform dependent behavior, not really sure.

I'm running this on red hat 6.7 with python 2.7.11, cffi 1.9.1, gcc 4.4.7 (yup our compiler is old)

EDIT
ahah, I spoke a little too soon. Apparently anonymous structs/unions are not allowed in C99 (however they are allowed in gnu99). See [this](http://stackoverflow.com/questions/1972003/how-to-compile-c-code-with-anonymous-structs-unions?rq=1) SO post.

**Comment by mgeier** [comment]
Thanks for reporting this!

I was aware that I'm using the C99 feature "flexible array members".
I'm OK with other C99 features, I think after one and a half decade we should be allowed to use "new" features ...

I'm reluctant to add `-std=c99` to the compiler options, because I fear that it will break on other compilers. Won't it?

Regarding the anonymous union, I wasn't aware that this isn't standard C (before C11). TBH, I didn't know before if this was possible or not. I just tried it and it seemed to work ...
I have nothing against adding a name to make it non-anonymous.
Which name would you suggest?
Feel free to make a PR if you like ...

**Comment by tgarc** [comment]
You're right about using c99 flag, apparently visual studio before 2015
doesn't even support it. On a related note, stdbool.h is also platform
dependent. I don't know if it's a c99 thing but I know visual studio
doesn't provide it.

I know these arent really big issues since this project is still taking
shape but I figured it's good to know they're there.

**Comment by mgeier** [comment]
Thanks! I very much appreciate your pointing out issues, be it small or big.

I'm using `bool`/`true`/`false` extremely rarely, so I could probably get rid of them completely.

I might replace the one `bool` used in the header file with an integer and some bit-wise flags that I could use if I need more information transported.
This is all likely to change. If you need some short-term changes to get it compiled, feel free to make PRs!

**Comment by mgeier** [comment]
@tgarc I've created #8 to solve the `stdbool.h` problem, can you please check if that's OK?

About the anonymous union, do you have a suggestion for a name to un-anonymize it?
Or a different solution?

**Comment by tgarc** [comment]
I'll check it when I get back to a windows machine. But when I compiled on my linux machine I didn't get the anonymous union error anymore...so something changed (I don't think my machine has changed since then).

**Comment by larsoner** [comment]
> Does anyone still get the "anonymous union" error?

I would trust CIBUILDWHEEL to find these. IIRC it uses old versions of Linux / Windows / macOS to build. To make maintenance easier, we can implicitly accept that the minimum build requirements are whatever CIBUILDWHEEL uses.

Looks like this issue predates our wheel building, and also uses Python 2.7 which is no longer supported. My vote is to close as WONTFIX

**Comment by mgeier** [comment]
Sounds good!

I'm closing this, but we can revisit it if somebody encounters problems.
