### ISSUE TITLE
Jitter in the actual_time of the action

### ISSUE THREAD

**Issue by PierreYvesH** [spatialaudio/python-rtmixer#46]
Hi,

I am currently working on a project where I'd like to sync some timestamps, if possible with sub-millisecond precision. I cannot use the `allow_belated = False` because that would end up not doing the action (running on Windows and with other application open which may delay too much).

Therefore I needed to find the time at which the sound is really played. To play the signal I use a RingBuffer (for looping capabilities) and register the action. I then wait until the action has an actual time and use it as my ground 0.

```python
stream = rtmixer.Mixer()
action = stream.play_ringbuffer(ringbuffer)

while action.actual_time == 0:
    pass

realStart = action.actual_time
```

However if I use a signal that is set (for example 2 sines of 500ms that start at 0.5s and 1.5s respectively) and use LSL to record both the output of my sound card and timestamps that signal the start and stop of the previous sines, I get a jitter in the accuracy of the actual_time around 6ms. 
I can only think of it coming from the actual_time as the measurement within the loop are set timestamps.

**Comment by mgeier** [comment]
What host API are you using?

The timing accuracy can be very different in different Windows host APIs.

BTW, it is not great to access `action.actual_time` while it is potentially written to in the callback function, even worse if it's done in a tight loop.

Currently, there is no special function for waiting for an action to begin, but you can probably use something like this as a work-around:

```python
action = stream.play_ringbuffer(ringbuffer)
stream.wait(stream.play_buffer(b'', channels=1))
realStart = action.actual_time
```

This way, you can make sure that `action.actual_time` is never accessed at the same time from two different threads.

I've used something similar in https://github.com/spatialaudio/python-rtmixer/blob/master/examples/delay.py.

**Comment by PierreYvesH** [comment]
I was using WASAPI, DirectSound had an awful jitter and switching to MME was way better (sub-millisecond), altough I can see sort of drift in realStart value, this is only due to the host-API then?
I switched to your way to get the actual_time value, thank you for the improvement.

**Comment by mgeier** [comment]
> altough I can see sort of drift in realStart value, this is only due to the host-API then?

The choice of host API definitely plays a big role here.

I'm not sure how you measure your timings, but you should keep in mind that the `actual_time` value is in a way quantized to the block duration if you use `start=0` (or at least something smaller than the current time) and `allow_belated=True` (i.e. the default values).

In this case, the `actual_time` value is set there:
https://github.com/spatialaudio/python-rtmixer/blob/6147a3a34cfac7ab30ba046d8934aa225df64791/src/rtmixer.c#L179

PortAudio provides the time value at the beginning of the block (and playback will start at the beginning of the block), so this value will always be on a grid with a resolution of the block duration.

So I would expect some jitter in the magnitude of one block duration between the Python code (e.g. when calling `stream.time`) and the value stored in `actual_time` (in addition to whatever the Python interpreter causes).

However, any jitter between features of the audio signal and the `actual_time` should be the fault of the host API (or the hardware, or whatever).

If you want to avoid the block quantization (at the cost of added latency), you should use a large enough `start` value and `allow_belated=False`. Even if you don't want to use it in the end, this might be helpful to diagnose your jitter problems.
