### ISSUE TITLE
Input Gain Data

### ISSUE THREAD

**Issue by andrew-mitchell-721** [spatialaudio/python-rtmixer#50]
This isn't an issue, per se, but I'm having trouble finding any documentation and hoping someone can help.

I'm trying to use rtmixer to develop software that sends a webhook request any time an input device's gain level crosses a predetermined threshold. I have to imagine this is possible using a combination of rtmixer and sounddevice, as the plot_input.py example file is able to plot the input gain of my mic.

Is there an attribute that I can call that will, at any given moment, return some representation of the relative (or absolute) input gain being collected by a stream?

Thanks in advance!

**Comment by mgeier** [comment]
No, doing any calculations based on the audio data is out of scope.

Also, there are many ways to calculate an "input gain". You could just check if the signal value crosses a threshold, but you might also want to consider the negative part of the waveform. Either way, you'll probably have to check for excessive DC offset. Maybe you could calculate an RMS (root mean square) value? You can use moving filters of many kinds. If you are interested in voice signals, you could check out VAD (voice activity detection). There are certainly many more avenues for you to explore ...

You can try to find a Python library that does this for you, then you could use `rtmixer` with ring buffers, but at a cost of increased latency and maybe CPU load.

You could also try to find a C library (or write your own C code), which you could then use in a similar way how `rtmixer` implements its audio callback. In other words, you cannot use `rtmixer` directly, but you can use it as a model for your own Python module that uses C code in the audio callback.
