### ISSUE TITLE
Python: portaudio can't update audio device [Mac]

### ISSUE THREAD

**Issue by KiDo-Ruan** [spatialaudio/python-rtmixer#51]
I install portaudio by homebrew (brew install portaudio) then I use `sounddevice.query_devices()` to get all available device on my Mac, but when I change device and recall `sounddevice.query_devices()` that not update new device.
I tried to use this :
`sd._terminate()`
Change device:
`sd._initialize()`
but I can't update new device when I recall `sounddevice.query_devices()`

How do I fix it in my project? Thanks for your answer!

**Comment by mgeier** [comment]
See https://github.com/spatialaudio/python-sounddevice/issues/443
